development:
  adapter: postgresql
  pool: 5
  # these are our new parameters
  encoding: UTF-8
  database: serler_development
  host: localhost
  username: jyo12
  password: dylantheman12

test:
  # this won't work 
  adapter: postgresql
  encoding: unicode
  database: serler_test
  pool: 5
  username: jyo12
  password: dylantheman12

production:
  # this won't work 
  adapter: postgresql
  encoding: unicode
  database: serler_production
  pool: 5
  username: jyo12
  password: dylantheman12